### ISSUE TITLE
How to use this?

### ISSUE THREAD

**Issue by E3V3A** [Okroshiashvili/Data-Science-Lab#1]
I'm looking to learn more about AI/ML etc. 
And your repo sounded promising, except there's not a single clue about how to implement or run any of it!

Could you provide some instructional examples or perhaps even other sources for learning?

**Comment by Okroshiashvili** [comment]
Hi,

I'm glad you found it useful. I think, on the repo there are only .py files and they must be independent. So, you'll be able to run them in any IDE or terminal.

Please, note that I did not update repo to incorporate several changes in dependencies (Did not find time for doing so). I mean Python packages such as sklearn, Pandas, numpy and more. So, if you run them, they may introduce some bugs or depreciation warnings. Then it's up to you to correct them and even you can send PR.

I suggest learning Python first, then return these materials and review them. You'll see how easy they are.

Feel free to ask further questions

P.S thanks for commenting and suggesting to update repo. I'll do my best to do it ASAP.

**Comment by Okroshiashvili** [comment]
I did some reorganization and update of the repo. Please, see and pull it. More is on the way :+1:
